### PR TITLE
update to toast-ui v3

### PR DESCRIPTION
**Pull request by miguelcobain**
This updates the underlying toast editor to the latest breaking change v3.
We should also do a major version bump.

Breaking changes:
- `@linkAttribute` argument renamed to `@linkAttributes`
- `@onStateChange` action argument renamed to `@onCaretChange`
- only the browsers above Internet Explorer (IE) 11 will be supported
- `@useDefaultHTMLSanitizer` argument was removed

Changes:
- new `@theme` argument
- new `@customMarkdownRenderer` argument
- new `@widgetRules` argument
- `@toolbarItems` no longer uses a "divider" item in the array. Instead pass in multiple arrays, and they will be divided in the UI.

For more info on the changes, check the v3 migration guide: https://github.com/nhn/tui.editor/blob/master/docs/v3.0-migration-guide.md

Notes:
- I added the destroy hook. I don't know if that makes a difference, but I think it's always safer to be "well behaved" and ask toast ui to destroy itself. Who knows if some kind of memory leak could be there without us knowing it.

### CODE REVIEW

**Comment by miguelcobain** [comment]
@ttill what do we need to move this forward? :)

**Comment by ttill** [comment]
Thanks for you effort @miguelcobain  and sorry for the lack of response. Not active in the software sphere currently…
This needs to be documented in both Readme and Changelog, but otherwise it is good to go

Given your repeated contributions, would you be interested in becoming a maintainer of this project? May I grant respective access to you?

**Comment by miguelcobain** [comment]
Yes, documentation would be needed. I think I outlined most of it in my comment.

Yes, I would be happy to help maintain this addon. :+1:

**Comment by ttill** [comment]
You were just given access to this repo as well as to the npm registry. I am very happy to have you on board and as I am currently not active as a developer at all you may freely move ember-tui-editor forwards. Thanks!

**Comment by miguelcobain** [comment]
Thank you. :)

**Pull request merged**
